### ISSUE TITLE
Spinning on `Create new wallet`

### ISSUE THREAD

**Issue by 0xalank** [PelagusWallet/pelagus-extension#113]
Requires a page refresh to move to seed phrase

![Screenshot from 2023-10-11 22-31-34](https://github.com/PelagusWallet/pelagus-extension/assets/14866363/5f4d27c2-cf7a-4dcc-8b5c-a2083eedc231)

**Comment by jdowning100** [comment]
@alanorwick I believe this was fixed in the latest release. Can you confirm?
