### ISSUE TITLE
BIP42 paths should use testnet coin type

### ISSUE THREAD

**Issue by wizeguyy** [PelagusWallet/pelagus-extension#119]
### Discord Discussion Link

na

### What would you like to be able to do?

Today, some wallets are derived on coin-type 60 (Ethereum) and 994 (quai), but all wallets should be derived on coin-type 1 (testnet).

What needs to happen:
* new wallets should be generated on coun-type 1
* imported wallets should default to coin-type 1
* an advanced option should be presented at import to import `legacy' wallet on 60 or 994

**Comment by Juuddi** [comment]
Fixed
