### ISSUE TITLE
Low text visibility on Connect to dApp screen

### ISSUE THREAD

**Issue by FlukyBlock** [PelagusWallet/pelagus-extension#130]
### Discord Discussion Link
https://discord.com/channels/1105993972247175229/1117868165771317459/1183896434991452230

### What browsers are you seeing the problem on?
All

### What would you like to be able to do?
I would like to be able to read easily the text "dApp would get permission to:"  on the Connect to dApp view.

### What is the problem?
The white text on a light grey background makes it difficult to read.

### Screenshot
![image](https://github.com/PelagusWallet/pelagus-extension/assets/150796316/4f367483-d923-4d9f-9e63-bfc69a2b8718)

**Comment by FlukyBlock** [comment]
I can take this one. It's already fixed on my fork. I'll submit a PR ASAP

**Comment by Juuddi** [comment]
Closed by #131
