### ISSUE TITLE
eth_chainId method does not exist

### ISSUE THREAD

**Issue by Denis2626** [PelagusWallet/pelagus-extension#132]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Trying to log into Galxe. Able to succeed with metamask but not pelagus. 

### What did not work?

Getting an eth_chainId method does not exist in console
![image](https://github.com/PelagusWallet/pelagus-extension/assets/23619112/c34464e7-d39b-450f-b675-919444ffe8bd)

### Version

None

**Comment by Juuddi** [comment]
Closed by #133
