### ISSUE TITLE
[Wallet Setup / Recovery] Wallet Creation Fails when network connection is not found

### ISSUE THREAD

**Issue by Juuddi** [PelagusWallet/pelagus-extension#135]
### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Prerequisite: network connection must be down (RPC nodes/endpoints responding with 502 code)

1. Download the Pelagus extension
2. When webUI loads, click create wallet
3. Create a password, click "Anchors Away" button
4. Get to seed phrase creation page, click "Create Recovery Phrase" button
5. Next page loads as blank with only back button rendered

### What did not work?

Seed phrase generation page does not load or render any content, seed phrase creation does not work because of this, cannot progress any further in install flow.

### Version
Version 0.2.9

### Relevant log output

![Screenshot 2024-01-24 at 4 43 40 PM](https://github.com/PelagusWallet/pelagus-extension/assets/98721462/1a002e9e-556d-4169-b48f-8c5e229d1c2c)

**Comment by rileystephens28** [comment]
The error logs in the screenshot above may be a bit misleading. The `Could not detect network` error is caused because there is no local node running, not because there is an issue connecting to the remote network. I believe this issue may be related to the #150 and #143 keyring service issue. @booleksandra can you please confirm whether this issue still exists on the latest build?

**Comment by booleksandra** [comment]
> The error logs in the screenshot above may be a bit misleading. The `Could not detect network` error is caused because there is no local node running, not because there is an issue connecting to the remote network. I believe this issue may be related to the [#150](https://github.com/PelagusWallet/pelagus-extension/issues/150) and [#143](https://github.com/PelagusWallet/pelagus-extension/issues/143) keyring service issue. [@booleksandra](https://github.com/booleksandra) can you please confirm whether this issue still exists on the latest build?

This bug is no longer reproduced in the latest build.
