### ISSUE TITLE
isPelagus undefined when Pelagus not set to default wallet

### ISSUE THREAD

**Issue by Juuddi** [PelagusWallet/pelagus-extension#136]
### What browsers are you seeing the problem on?

Chrome, Brave

### What were you trying to do?

In my application, I am trying to initiate a Pelagus connection if and only if `window.ethereum.isPelagus` is set to true. This allows me to only send a connection request to the Pelagus extension, regardless of whether Metamask or other EVM enabled wallets are present in the browser.

This logic works correctly when Pelagus is set as the default wallet, which returns `isPelagus=true` and `isMetamask=false`.

### What did not work?

This logic works incorrectly when Pelagus is not set as the default wallet and returns `isMetamask=true` and `isPelagus=undefined`.

When `isPelagus` is set as undefined, it proves quite difficult to correctly access Pelagus and not other EVM based browser extension wallets. In my opinion,`isPelagus` should always be set to true and `isMetaMask` should be toggled when the default wallet setting is changed by the user. (Might even consider removing `isMetaMask` entirely as Pelagus is not built to interface with traditional EVM chains.)

### Version

None

### Relevant log output

```shell
// Pelagus set as default wallet
> window.ethereum.isPelagus
< true
> window.ethereum.isMetamask
< false

// Pelagus not set as default wallet
> window.ethereum.isPelagus
< undefined
> window.ethereum.isMetamask
< true
```

**Comment by rileystephens28** [comment]
This is issue is caused by other wallet providers overwriting `window.ethereum` and is not unique to Pelagus. 

Dapps can resolve the Pelagus wallet provider (if available) using this line of code
```const provider = window.ethereum.providers?.find((provider) => provider.isPelagus ) || window.ethereum```
