### ISSUE TITLE
Unable to import account "logger.ts:209 Async thunk failed TypeError: Cannot read properties of undefined (reading 'addresses')"

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/pelagus-extension#137]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Trying to import a seed phrase to Pelagus

### What did not work?

When importing seed phrase, on clicking "import account" the website hangs and gets stuck. When looking at the console, the error is:
logger.ts:209 Async thunk failed TypeError: Cannot read properties of undefined (reading 'addresses')
    at keyrings.ts:69:46
    at async utils.ts:129:9

Running latest version of Pelagus on the chrome store.

### Version

None

**Comment by booleksandra** [comment]
@rileystephens28  The same bug is reproduced when creating a new wallet.

**Test environment**:
Browser - Google Chrome, Version 123.0.6312.87

**Steps to reproduce when logging in with an existing wallet**:
1. Download the [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar)
2. Wait 5+ minutes (do not log in)
3. Click on [Use an existing wallet].
4. Click on import recovery phrase 
5. Fill in the password fields
6. Click [Anchors Away!].

**Expected result**:
User is redirected to another step to fill in the "Import recovery phrase" field.

**Actual result**:
After clicking on the [Anchors Away!], nothing happened, the user remained on the page for entering the password

**Steps to reproduce when you log in and create a new wallet**:
1. Download the [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar)
2. Wait 5+ minutes (do not log in)
3. Click on [Create new wallet].
4. Fill in the password fields
5. Click [Anchors Away!].

**Expected result**:
User is redirected to a page that warns about the creation of a recovery secret phrase.

**Actual result**:
After clicking on the [Create new wallet], user redirected on the page for entering the password


![Image](https://github.com/PelagusWallet/pelagus-extension/assets/141249813/36f52da5-8db2-4aae-b522-069f65f49730)
