### ISSUE TITLE
quai_requestAccounts doesn't work until several seconds after the webpage has loaded

### ISSUE THREAD

**Issue by robschleusner** [PelagusWallet/pelagus-extension#138]
### What browsers are you seeing the problem on?

Chrome, Brave

### What were you trying to do?

Connect pelagus to website (https://marginex.app/)

### What did not work?

When I press "Connect with Cyprus 2", then try to connect from Pelagus, the connection doesn't go through. There are some logs in the console (specifically:  `content: inpage > background: {"id":"2","target":"tally-provider-bridge","request":{"method":"quai_requestAccounts","params":["MarginEX","https://marginex.app/favicon.ico"]}}`) that indicate the request is being sent correctly, but nothing is ever returned.

If I take ~5 seconds between the page loading and trying to connect, it does work. I imagine that the accounts are not loading in fast enough so when the request accounts is not working correctly at first.

### Version

None

### Relevant log output

```shell
Within ~4 seconds of page load: 
provider-bridge.js:1131 - 
content: inpage > background: {"id":"2","target":"tally-provider-bridge","request":{"method":"quai_requestAccounts","params":["MarginEX","https://marginex.app/favicon.ico"]}}

If I wait a second, we can see the call and the account response:
provider-bridge.js:1131 - 
 content: inpage > background: {"id":"3","target":"tally-provider-bridge","request":{"method":"quai_requestAccounts","params":["MarginEX","https://marginex.app/favicon.ico"]}}
provider-bridge.js:1136 -
content: background > inpage: {"id":"3","jsonrpc":"2.0","result":["0x1e04cabf989002979c51719369f48d2fd857d514"]}
```

**Comment by Juuddi** [comment]
https://github.com/PelagusWallet/pelagus-extension/assets/98721462/dd85b599-6e62-4d78-bd57-4aca60a1c4fb

**Comment by Juuddi** [comment]
Here it took a total of 12 presses of the connect button and confirm in the wallet to get the extension to return accounts to the application:
![Screenshot 2024-02-05 at 7 55 41 PM](https://github.com/PelagusWallet/pelagus-extension/assets/98721462/bfc65e7c-a980-4fd4-bbae-fa59136888bc)

**Comment by jdowning100** [comment]
<img width="555" alt="Screen Shot 2024-02-06 at 10 23 46 AM" src="https://github.com/PelagusWallet/pelagus-extension/assets/26939949/ba7fbefa-204e-4f8b-96a0-41265ecc8c5a">

 I'm unable to replicate this issue. The dapp shows that the pelagus provider is not found, but window.ethereum returns the provider.
 Edit: Looks like this is issue is related to https://github.com/PelagusWallet/pelagus-extension/issues/136

**Comment by Juuddi** [comment]
As far as #136 goes, majority of the sites use `window.ethereum.isPelagus()` to identify the Pelagus provider, which is returned as undefined if Pelagus is not set as the default wallet. You can by pass the `No Pelagus provider found` issue by setting Pelagus as the default wallet.
