### ISSUE TITLE
SUGGESTION: Grind addresses to give each new user a Cyprus-1 address for their first account

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/pelagus-extension#140]
### Discord Discussion Link

N/A

### What would you like to be able to do?

I would like a Cyprus-1 address by default when creating a new wallet, especially as we begin prioritizing single-chain development (and try and aggregate activity onto C1)

**Comment by rileystephens28** [comment]
This will come in a future quais sdk update.

**Comment by rileystephens28** [comment]
@ArtemBurakov you should be able to do this implementation using quais5 then update to quais6 to ensure Qi (UTXO token) support.

**Comment by booleksandra** [comment]
Verified
