### ISSUE TITLE
PELAGUS WALLET CONNECTION PROBLEM

### ISSUE THREAD

**Issue by LIHebzy1** [PelagusWallet/pelagus-extension#141]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I was trying to play the Developer game and connect to Dapp currently active

### What did not work?

1. Set as default and without that the wallet can function properly isn't the Best because there are other wallet extension in Browser
2. I have to use a new Browser to use dapp is stressful also lies a threat from always importing Secret Phrase

This has made explorer dapp easily, there need to be a fix before the next testnet so the wallet can function properly

### Version

None

**Comment by rileystephens28** [comment]
Thank you for the feedback.

What version of the extension are you using?

What operating system are you using?

Are you unable to connect with the currently active dapp at all when other wallet extensions are installed and Pelagus is set as the default wallet?

**Comment by LIHebzy1** [comment]
Recent Version
Linux
Yes, I couldn't connect

**Comment by rileystephens28** [comment]
We have come up with a solution that allows dapps to explicitly select Pelagus for connection requests without having to set Pelagus as the default wallet. We are communicating this to our builders and updating the docs today. As this solution does not require modification to Pelagus, I am closing this issue.
