### ISSUE TITLE
BUG: Pelagus extension icon is unresponsive after going through initial setup flow

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/pelagus-extension#143]
### Discord Discussion Link

https://discord.com/channels/887783279053406238/905873038971637823/1209230256624500756

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

When going through the Pelagus flow in the browser, upon completion (when the Pelagus extension icon is added to the browser extensions), clicking the Pelagus icon does not open the wallet. 

### What did not work?

Clicking the Pelagus icon does not open the wallet after going through the signup flow. The only way to get around this is to remove the extension, re-add it, and go through the signup flow again. On latest version.

### Version

None

**Comment by ArtemBurakov** [comment]
can you provide more context:
1) when you installed the pelagus extension
2) added to the list (or it will be added automatically)
3) opened pelagus onboarding and successfully completed sign-up

after that the wallet will show "Welcome to Pelagus" and here if you try to open the extension by clicking on it in browser menu it won't open?

or did you mean that when you are already on the registration page and click on the extension icon in the browser menu, it doesn't open?
