### ISSUE TITLE
[Pelagus] - Add address doesn't redirect user back to add address screen

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#152]
Problem:

If the wallet is locked ahead of time, and then adds an address, it redirects the user to a sign in screen. After signing in, the user is redirected to the home screen, not the add address screen.

What needs to be fixed:

1. After clicking the add address screen in a locked wallet, the user should redirect to enter their password
2. After entering their password, they should be redirected to the add address screen, with a new address that is added.
3. When a user clicks a certain address after adding one, they should be redirected to the home screen with whatever address they added.

**Comment by booleksandra** [comment]
Test environment:
Browser - Google Chrome, Version 123.0.6312.107

**Precondition**: 
1. [Extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar) should be installed and the user must be logged in
2. Signing should be locked

**Steps to reproduce** :

1. Open "Accounts" tab
2. Click on "Add Address".
3. Fill in the signing password fields
4. Click [Unlock].

**Expected result**:
Opened a tab to select the required address.

**Actual result**:
User is redirected to to the main page.

**Comment by booleksandra** [comment]
Tested, the bug is not reproducible.
