### ISSUE TITLE
[Pelagus] - Delete my data button on Analytics Settings screen does nothing

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#154]
This may end up being a GDPR issue if not addressed.

**Comment by rileystephens28** [comment]
Since there is no remote datastore component to Pelagus, this only pertains to any analytics we gather about usage data. To be clear, when a user requests that their data be deleted, only PII (Personal Identifiable Information) will be scrubbed from the data such as addresses.

**Comment by rileystephens28** [comment]
Same as #153 lets just hide for now
