### ISSUE TITLE
Activity tab of default address throws error and shows "Return Home" button

### ISSUE THREAD

**Issue by rileystephens28** [PelagusWallet/pelagus-extension#168]
What browsers are you seeing the problem on?
Chrome

What were you trying to do?
View transaction activity for defaut (cypress 1) address

What did not work?
Viewing the activity tab for all addresses works except default cypress 1 address. This causes the error `Cannot read properties of null (reading 'slice')` to be thrown, which is handled in the UI by showing a button that says "Return Home".

Note
I have not confirmed whether this is an issue with cypress 1 addresses or the first available address in the accounts array, however, I suspected the latter.

https://github.com/PelagusWallet/pelagus-extension/assets/24363438/a7dfa27a-a91b-4dbb-8cdc-c0bd950bea48

**Comment by ArtemBurakov** [comment]
Could you please provide instructions on how I can recreate this? Transactions are currently down, so I don't have any data to view.

**Comment by rileystephens28** [comment]
A team member was experiencing this, so unfortunately I don't know the steps to recreate. It looks like the error is occurring on either [here](https://github.com/PelagusWallet/pelagus-extension/blob/b5404d4aea491784555b860e26ebc54d7036dc98/ui/components/Wallet/WalletActivityListItem.tsx#L145) or [here](https://github.com/PelagusWallet/pelagus-extension/blob/b5404d4aea491784555b860e26ebc54d7036dc98/ui/components/Wallet/WalletActivityListItem.tsx#L152) when trying to truncate address. It appears what is causing this is that `activityViewDetails.recipient.address` or `activity.from` is undefined.

**Comment by booleksandra** [comment]
Bug is not reproducing.
