### ISSUE TITLE
Extension sometimes shows a blank page when opened

### ISSUE THREAD

**Issue by jdowning100** [PelagusWallet/pelagus-extension#18]
### Discord Discussion Link

N/A

### What would you like to be able to do?

I have noticed that the extension page sometimes shows a blank page when opened. Need to view logs and debug further to discern exactly why. To fix, either close and reopen the extension or turn the extension off and on (in Chrome Manage Extension).

**Comment by Denis2626** [comment]
Is this what the issue is referring to ?

![image](https://github.com/PelagusWallet/pelagus-extension/assets/23619112/bb4562ad-5a5c-457c-99c8-9f92d2091580)

**Comment by jdowning100** [comment]
> Is this what the issue is referring to ?
> 
> ![image](https://user-images.githubusercontent.com/23619112/270723511-bb4562ad-5a5c-457c-99c8-9f92d2091580.png)

That is not what I'm referring to - the extension sometime shows a completely blank page when opened and cannot be used until it's restarted. I believe this is related to https://github.com/PelagusWallet/pelagus-extension/issues/89
