### ISSUE TITLE
Wrap commit in "<>" at bottom of settings page

### ISSUE THREAD

**Issue by rileystephens28** [PelagusWallet/pelagus-extension#189]
Right now the version number and commit hash are being joined together as a single string. Strangely this only happens when the commit hash is defined. When the commit has is undefined the commit hash is correctly wrapped in <> as `<unknown>`.

Extension version and commit hash should have the format **Version version-number <commit-hash>** If the hash is not provided then show nothing other than version

![Image](https://github.com/PelagusWallet/pelagus-extension/assets/24363438/f4fda408-83d1-4b04-9f04-c00b3b58147f)
This image shows version `0.2.11` and commit hash `7691aa5`

**Comment by booleksandra** [comment]
Verified.
