### ISSUE TITLE
Remove old wallet related UI elements

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#19]
### Discord Discussion Link

https://discord.com/channels/1105993972247175229/1117868165771317459/1141672692634890362

### What would you like to be able to do?

Extension still contains UI elements from forked wallet. Here is the examples:

- [x] 1. Animation recommending to pin extension after creating/importing wallet.
- [x] 2. Icon on Importing wallet screen (`/onboarding/import-seed`)

**Comment by Friedheilm** [comment]
<a href="https://ibb.co/YZYZG57"><img src="https://i.ibb.co/YZYZG57/Screenshot-from-2023-08-16-15-16-06.png" alt="Screenshot-from-2023-08-16-15-16-06" border="0"></a>
<a href="https://ibb.co/8nwvbXK"><img src="https://i.ibb.co/8nwvbXK/Screenshot-from-2023-08-17-12-05-44.png" alt="Screenshot-from-2023-08-17-12-05-44" border="0"></a>

**Comment by jdowning100** [comment]
Fixed in https://github.com/PelagusWallet/pelagus-extension/pull/35

**Comment by Friedheilm** [comment]
Point 1 is still a thing in 0.2.0-rc.0 version, when user adds/creates account for the first time.

**Comment by Friedheilm** [comment]
Fixed.
