### ISSUE TITLE
Make the "Pelagus is not your default wallet" notification at the top of the wallet dismissible

### ISSUE THREAD

**Issue by rileystephens28** [PelagusWallet/pelagus-extension#192]
Add an `X` button to the left of the blue word "Pelagus" that will cause this notification to stop showing. This will have to persist between uses so will likely need to be stored with other user preferences in indexDB

![Image](https://github.com/PelagusWallet/pelagus-extension/assets/24363438/0d406d1a-bc00-4bb6-84d7-de5bb3b745ab)

**Comment by booleksandra** [comment]
Verified.
