### ISSUE TITLE
[Create new wallet]: After creating a password, a blank page is loaded

### ISSUE THREAD

**Issue by rileystephens28** [PelagusWallet/pelagus-extension#193]
**Test environment**:
Browser - Google Chrome, Version 123.0.6312.107

**Steps to reproduce** :

1.Download the [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar)
2. Click on [Create new wallet].
3. Fill in the password fields
4. Click [Anchors Away!].
5. Wait 5+ minutes 
6. Сlick on [Create recovery phrase]

**Expected result**:
User is redirected to another step with a recovery phrase to save and store it.

Actual result:
After clicking on the [Create recovery phrase], a user is redirected to a blank page

Attachments:
[Screenshot](https://drive.google.com/file/d/13e7_lm5mm4YnFCp9KxtX2eZ-OPpRybHF/view?usp=sharing)

**Comment by booleksandra** [comment]
Tested. After Michael's updates, the bug is still reproduced.
