### ISSUE TITLE
[Send Asset]: The "back" button covers text on the page

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#199]
**Test environment**:
Browser - Google Chrome, Version 123.0.6312.107

**Preconditions**:

[Extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar) should be installed and the user must be logged in

**Steps to reproduce** :

1. Click on [Send]
2. Fill in "Send To:" field
3. Click on "Advanced" link
4. Scroll to the end

**Attachments**:
[Screenshot](https://drive.google.com/file/d/1A4XIewnUxR1BmBhv64TKSQCB0qRhrive/view?usp=sharing)
[Video](https://drive.google.com/file/d/1XhRBylhw7G7ViYaRVzslxiC77I8e7Zb0/view?usp=drive_link)

**Comment by booleksandra** [comment]
Second bug with text displacement:

**Preconditions**:

[Extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar) should be installed and the user must be logged in

**Steps to reproduce** :

1. Click on [Send]
2. Fill in "Send To:" field with incorrect data (e. g. 0x07b7a166fee3c923f707cb1d529295abd3404f7)
3. Click on "Advanced" link
4. Scroll to the end
5. Pay attention to the text "Address could not be found"

**Expected result**:
The text "Address could not be found" is placed under the "Send to" field

**Attachments**:
[Video](https://drive.google.com/file/d/1matXmxCP2C0MKUOUP-OSllU3QynrZfbN/view?usp=sharing)

**Comment by booleksandra** [comment]
Verified
