### ISSUE TITLE
Total account balance: value is displayed incorrectly when lower then 0.1

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#20]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

**Steps to reproduce:**

1. Send less then 0.1 QUAI tokens to address that has 0 QUAI;
2. Select this address in the list;
3. Check balance on main screen;

**Expected result:** displayed token amount should be equal to to amount from step 1.

### What did not work?

**Actual result:** Balance isn't displayed in proper format, decimals that should be after point displayed before it. 
<a href="https://ibb.co/ck3YfbL"><img src="https://i.ibb.co/ck3YfbL/Screenshot-from-2023-08-17-13-28-33.png" alt="Screenshot-from-2023-08-17-13-28-33" border="0"></a>

### Version

v0.38.1

**Comment by Friedheilm** [comment]
In addition to that, values that are lower than 1*10^(-10) cant be transformed into number and are displayed as NaN.
<a href="https://ibb.co/GTV1cCs"><img src="https://i.ibb.co/GTV1cCs/Screenshot-from-2023-08-16-14-52-14.png" alt="Screenshot-from-2023-08-16-14-52-14" border="0"></a>

**Comment by jdowning100** [comment]
Fixed in https://github.com/PelagusWallet/pelagus-extension/pull/21

**Comment by Friedheilm** [comment]
Fix verified.
