### ISSUE TITLE
[Set Password]: The "password" field successfully accepts all characters and spaces

### ISSUE THREAD

**Issue by rileystephens28** [PelagusWallet/pelagus-extension#205]
**Test environment**:
Browser - Google Chrome, Version 123.0.6312.107

**Steps to reproduce** :

1. Download the [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar)
2. Click on [Use an existing wallet].
3. Click on [import recovery phrase]
4. Enter a password that contains insecure characters, such as non-Latin letters, lowercase letters only, spaces, or special characters.(e.g." fcjhb.   uапспрпуиві!"%:,;()_ ")
5. Click [Anchors Away!].

**Expected result**:
A warning message about an incorrect password appears.
**Actual result**:
User is redirected to another step to fill in the "Import recovery phrase" field.

**Comment by rileystephens28** [comment]
New password validation:

- only allow letters from latin alphabet
- do not allow spaces

If either of these cases are violated then we should display an error message like the existing ones that show when you attempt to create a password with fewer than 8 characters

**Comment by booleksandra** [comment]
Tested. The Password field is now accepted:
- Latin letters only
- Numbers.
- Special characters( ! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ )

If the field is filled in with incorrect entries, the following message appears:


![Image](https://github.com/PelagusWallet/pelagus-extension/assets/141249813/8c73f0a7-fa1e-4218-8ddd-2a0c092c90df)
