### ISSUE TITLE
Finalizing new wallet seed phrase failing

### ISSUE THREAD

**Issue by rileystephens28** [PelagusWallet/pelagus-extension#208]
Test environment:
Browser - Google Chrome, Version 123.0.6312.107

Steps to reproduce :

1.Download the [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar)
2. Click on [Create new wallet].
3. Fill in the password fields
4. Click [Anchors Away!].
5. Complete verify recovery phrase word match
6. Сlick on [Verify recovery phrase]
7. Click [Finalize]

Expected result:
User is redirected to Welcome to Pelagus page

Actual result:
After clicking on [Finalize] does nothing due to failure to deconstruct `success` value in `onVerifySuccess` method

![Image](https://github.com/PelagusWallet/pelagus-extension/assets/24363438/b623df51-92dd-417a-92a4-eea3e177268e)

@booleksandra I have only reproduced this once and a user also experienced this issue. Please attempt to reproduce.

**Comment by rileystephens28** [comment]
More context is available in [this](https://discord.com/channels/1116103236651323535/1164823341488685147) discord issue ticket

**Comment by booleksandra** [comment]
> Test environment: Browser - Google Chrome, Version 123.0.6312.107
> 
> Steps to reproduce :
> 
> 1.Download the [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar) 2. Click on [Create new wallet]. 3. Fill in the password fields 4. Click [Anchors Away!]. 5. Complete verify recovery phrase word match 6. Сlick on [Verify recovery phrase] 7. Click [Finalize]
> 
> Expected result: User is redirected to Welcome to Pelagus page
> 
> Actual result: After clicking on [Finalize] does nothing due to failure to deconstruct `success` value in `onVerifySuccess` method
> 
> ![Image](https://private-user-images.githubusercontent.com/24363438/322984397-b623df51-92dd-417a-92a4-eea3e177268e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODkyODgsIm5iZiI6MTcxMzc4ODk4OCwicGF0aCI6Ii8yNDM2MzQzOC8zMjI5ODQzOTctYjYyM2RmNTEtOTJkZC00MTdhLTkyYTQtZWVhM2UxNzcyNjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEyMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MDFjZTEyMmZjNDBjMjkzMDYyMTkyZGE4MGQ1ODI3OTk4ODA0MmYwZjQzZGRiZmFmMGQ2NDI1ZDcyNzQxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1HZ_u7R1jre6cs4wPbmKQWuncbUojapyipzIhsWkmfg)
> 
> [@booleksandra](https://github.com/booleksandra) I have only reproduced this once and a user also experienced this issue. Please attempt to reproduce.

This bug is reproduced continuously according to all the steps described in this task. 
The bug is reproduced even if you are on the page for less than a minute when you complete step 5
