### ISSUE TITLE
[Accounts]: When trying to unlock signing, nothing happens after clicking the "Unlock" button

### ISSUE THREAD

**Issue by rileystephens28** [PelagusWallet/pelagus-extension#216]
**Preconditions**:
- The [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar) must be installed and the user must be logged in
- There must be 2+ wallets in the "Accounts" tab
- Signing must be locked

**Steps to reproduce** :
1. Go to the "Accounts" tab
2. Click on "+ Add Address"
3. Fill in the password field
4. Click [Unlock].

**Attachments**:
[Video](https://drive.google.com/file/d/1_1xJ4IexzYNqf0oShX8uGm5OR_EZMfiP/view?usp=drive_link)

**Comment by booleksandra** [comment]
Verified.
