### ISSUE TITLE
If Pelagus wallet extension is enabled, Metamask extension is not recognized

### ISSUE THREAD

**Issue by camimancusi** [PelagusWallet/pelagus-extension#23]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Precondition
- Having Metamask extension installed with a wallet configured
- Set Pelagus wallet as default wallet

Steps
1. Try to connect in any page which requires metamask wallet having the pelagus extension disabled. Example: https://alpha.rare.xyz/
2. You are going to be able to connect your wallet correctly
3. Enable the pelagus extension
4. Do a refresh in the first page
5. Try to connect your wallet
6. You are going to see that Metamask is not recognized

### What did not work?

Metamask extension is not recognized in the browser while the Pelagus wallet extension is enabled

### Version

v0.38.1

**Comment by jdowning100** [comment]
Have you verified that Pelagus is not set as your default wallet in the settings?

**Comment by camimancusi** [comment]
yes, it was set as default wallet. However If I look for the extension of Metamask and I select it, I guess I should be able to continue but the Metamask extension is not recognized diretly

**Comment by jdowning100** [comment]
Please try not setting Pelagus as your default wallet and see if that fixes it

**Comment by camimancusi** [comment]
https://github.com/PelagusWallet/pelagus-extension/assets/103962159/719338db-9f64-4f6c-b624-a450a7b6c2ab

No, the issue keeps although the wallet is not set as default

**Comment by jdowning100** [comment]
The current solution for this is to disable Metamask when Pelagus is in use and disable Pelagus when Metamask is in use. This will prevent them from competing for the window.ethereum provider that dapps use.

**Comment by jdowning100** [comment]
The current solution for this is to disable Metamask when Pelagus is in use and disable Pelagus when Metamask is in use.
