### ISSUE TITLE
[Golden Age] - Header changes

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#237]
Refactor the header UI to match this screen: https://www.figma.com/file/opWFUbbMG2OT3N4jcfZRCs/Pelagus-Wallet?type=design&node-id=1265-740&mode=design&t=tpzeduyopteXrcE8-0 

Requirements:

- Network switcher is located on far left
- Account switcher is top middle; and currently selected address underneath. 
- Connected to site indicator is to the right of the account switcher, and looks like a globe.  When a user is conencted to the current site, the globe glows green.
- Settings hamburger is situated to the far right.

**Comment by booleksandra** [comment]
Verified
