### ISSUE TITLE
[Golden Age] - Network Selector - Change Network Selector to match Designs

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#239]
Requirement:

- Change componetns to match design
- When a user clicks on the network tab, it is a slide up drawer that appears.
- When the user clicks the x in the drawer, it closes
- The networks available on the goldenage branch are Golden Age 
- The toggle at the bottom of the drawer for developer mode, if clicked on shows the local network option
- There should not be an add network button at the bottom of the design (sorry about that)

Figma: https://www.figma.com/file/opWFUbbMG2OT3N4jcfZRCs/Pelagus-Wallet?type=design&node-id=1256-464&mode=design&t=tpzeduyopteXrcE8-0

**Comment by booleksandra** [comment]
Verified
