### ISSUE TITLE
[Golden Age] - dApp Connections selector

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#241]
Requirements:

- [ ] When a user clicks the dapp connector (the globe icon on the main page), a slide up drawer appears with accounts that are connected to this dApp 
- [ ] Each of the connected accounts will be displayed to the user
- [ ] When a user clicks the delete button, they discconect that account from the dApp
- [ ] There is a button at the bottom of the draw to disconnect all acccounts that are connected to the dapp
- [ ] When a user clicks that button to disconnect, they discconect all accounts from that dapp.

**Comment by booleksandra** [comment]
Tested. The following item in the description does not yet work: "When the user clicks the delete button, it disconnects this account from the dApp". Also, the function of switching between accounts does not work. For these functions to work, the logic part needs to be changed, we discussed this with Artem.
Also, during the testing, I found bugs related to connecting to the dApp. I will create separate issues for these bugs.
