### ISSUE TITLE
Wallet isn't opened by Alt+T combination

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#25]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

On attempt to open extension by Alt+T combination combination is recognized, keys on onboarding UI are highlighted when pressed.

### What did not work?

Extension doesn't open.

### Version

v0.38.1

**Comment by Denis2626** [comment]
Decided to to remove this per @jdowning100
