### ISSUE TITLE
[Golden Age] - Add Send Confirmation

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#250]
Using the reusable modal, add the send confirmation for when a user completes sending Quai (or QI later) to another wallet address.

COPY:

Headline

Body

**Comment by rileystephens28** [comment]
@MichaelKostroma 

## Success Copy

Headline: "Quai Sent!"

Body: "Your transaction was successfully submitted. "

I am not sure if the "View Transaction" link is part of the body but we do want to keep this also.

## Failure Copy

Headline: "Uh oh!"

Body: "An error occurred when submitting your transaction. Make sure the transaction you are submitting is valid and try again."

We do not want the "View Transaction" link to appear on failure.
