### ISSUE TITLE
Settings: unable to turn on analytics

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#26]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

When user finishes onboarding process notification about analytics being turned on by default appears. Click on this notification leads user to settings with ability to change analytics settings switch.

### What did not work?

Switch doesn't reacts to user clicks.

### Version

v0.38.1

**Comment by jdowning100** [comment]
"When user finishes onboarding process notification about analytics being turned on by default appears"
Can we verify that this is still happening?
Analytics are disabled and cannot be turned on - this is intentional.

**Comment by Friedheilm** [comment]
In the 0.2.0-rc.0 version there is no notification about analytics by the end of onboarding process.
