### ISSUE TITLE
Unlocking wallet: validation errors are displayed when correct password is entered

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#27]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

**Steps to reproduce:**

1. Add more than 1 wallet to extension;
2. Lock signing;
3. Attempt to unlock signing using incorrect password;
4. Unlock signing with correct password.

### What did not work?

`Signing unlocked!` message appears. But validation error about incorrect password is displayed.

### Version

v0.38.1

**Comment by jdowning100** [comment]
https://github.com/PelagusWallet/pelagus-extension/assets/26939949/5852841e-5ef0-4731-abf0-07c850d03c4f

I'm unable to replicate this issue. Google Chrome Version 115.0.5790.170 (Official Build) (arm64)

**Comment by Friedheilm** [comment]
Can't reproduce it either.
