### ISSUE TITLE
I can not send funds (Q) after a dropped tx

### ISSUE THREAD

**Issue by camimancusi** [PelagusWallet/pelagus-extension#32]
### Discord Discussion Link

https://discord.com/channels/1105993972247175229/1117868165771317459/1144261066294038558

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Preconditions
- Have funds in the wallet

Steps
-I tried to send funds (Q) in cyprus-1 net to an address 
- The transaction kept on 'pending to confirm'. 
- Today (24 Aug, 2023)  the status of the transaction is:
--------- In the wallet: status equal to 'dropped'
--------- In the quaiscan: unconfirmed - pending

* Transaction: https://cyprus1.colosseum.quaiscan.io/tx/0x28ad6bc1bd06438e9cc7049ae121d43356052df67fce3294ac1e0d2783faa3f0

* My address: 
* 0x08bcc8d7577cc551e2e49c6252318384301ca6b3

https://github.com/PelagusWallet/pelagus-extension/assets/103962159/d4bd37ea-b20d-45d1-b3ba-a98b6f7a6e88

Expected result
I should be able to send funds to another address and the status of the transaction should be consistent between wallet and quaiscan

### What did not work?

Obtained result
- The original transaction has two different status between wallet (dropped) and quaiscan (unconfirmed/ pending)
- When I try to do another transaction to send funds (Q), I can not continue

### Version

v0.38.1

### Relevant log output

```shell
tx: https://cyprus1.colosseum.quaiscan.io/tx/0x28ad6bc1bd06438e9cc7049ae121d43356052df67fce3294ac1e0d2783faa3f0

My address: 0x08bcc8d7577cc551e2e49c6252318384301ca6b3
```

**Comment by camimancusi** [comment]
I am trying to reproduce the error to attach the log in console

**Comment by camimancusi** [comment]
I'm not being able to reproduce since I'm not seing the corret funds in my wallet and the explorer returns me this error 
![image](https://github.com/PelagusWallet/pelagus-extension/assets/103962159/14ebab1a-a358-45df-9c88-86a3c041681f)

**Comment by jdowning100** [comment]
Hi, can you please try to reproduce this issue and attach service worker console logs? I am unable to reproduce this myself.

**Comment by camimancusi** [comment]
I close this issue since it seems to be resolved (I followed the steps and I can't reproduce it)
