### ISSUE TITLE
Send Page UI Requirements

### ISSUE THREAD

**Issue by jdowning100** [PelagusWallet/pelagus-extension#36]
### Discord Discussion Link

N/A

### What would you like to be able to do?

In the Send Page UI, we need to make the 'advanced' button prettier with highlight on hover and a carrot to indicate that it's a button. In addition, the 'to address' should wrap so that the user can see the entire address, and the advanced text boxes should look prettier in general.

**Comment by Denis2626** [comment]
resolved in #63
