### ISSUE TITLE
Small UI Tweaks

### ISSUE THREAD

**Issue by robschleusner** [PelagusWallet/pelagus-extension#41]
### What browsers are you seeing the problem on?

Chrome, Brave

### What were you trying to do?

Will put small UI tweaks on this issue report

### What did not work?

![Screenshot 2023-09-06 at 12 11 10 PM](https://github.com/PelagusWallet/pelagus-extension/assets/84946595/b8d55897-7292-406a-9b69-487ae014cfe5)

![](https://cdn.discordapp.com/attachments/1117868165771317459/1149015998863790080/Screen_Shot_2023-09-06_at_11.17.45_AM.png)

Photos above

### Version

None

**Comment by jdowning100** [comment]
Fixed in https://github.com/PelagusWallet/pelagus-extension/pull/78
