### ISSUE TITLE
Wallet name is undefined and new addresses do not utilize created icons

### ISSUE THREAD

**Issue by 0xalank** [PelagusWallet/pelagus-extension#42]
![Screenshot 2023-09-06 at 2 00 52 PM](https://github.com/PelagusWallet/pelagus-extension/assets/14866363/d9d6285d-6511-4eac-a883-058324e04558)

**Comment by 0xalank** [comment]
Assuming this is a UI issue so assigning to @DenisIvanov26

**Comment by jdowning100** [comment]
Wallet name undefined is fixed in https://github.com/PelagusWallet/pelagus-extension/pull/59
The second part is (I think) due to the RPC node being down at the time, so the wallet can't be loaded properly
