### ISSUE TITLE
Unable to check "Set Pelagus as your Default Wallet" Slider

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/pelagus-extension#43]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

When going through the setup flow on Chrome, I tried to click the slider to make Pelagus my default wallet and the slider did not respond. 

### What did not work?

The slider did not move or respond to clicks. 

### Version

v0.38.1

**Comment by jdowning100** [comment]
I tried to replicate this issue but the slider worked. Can you try it again on the latest version?
