### ISSUE TITLE
"Set Pleagus as Default Wallet" toggle doesn't work

### ISSUE THREAD

**Issue by dev-of-the-biz** [PelagusWallet/pelagus-extension#45]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I was trying to use the toggle to set Pelagus as default wallet when setting up a new wallet

### What did not work?

The toggle button didn't work (you couldn't click it)

### Version

None

**Comment by jdowning100** [comment]
Duplicate of https://github.com/PelagusWallet/pelagus-extension/issues/43
