### ISSUE TITLE
Aggregated ticket for UI issues introduced in 0.2.0-rc.0

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#46]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

After recent UI changes layout of some elements is broken and others are hardly visible.

### What did not work?

- [x] 1. Placeholder text on "Import phrase" screen is overlapped by field border.
- [x] 2. "Import account" label on locked button is barely readable
- [x] 3. Hotkeys for opening wallet aren't visible.
- [x] 4. "dApp would get permission to" label on connection screen is almost unnoticeable.

### Version

v0.38.1

**Comment by Friedheilm** [comment]
![Screenshot from 2023-09-06 16-19-23](https://github.com/PelagusWallet/pelagus-extension/assets/36986437/55062476-be04-49d7-aa61-dd309f87c640)
![Screenshot from 2023-09-07 12-15-06](https://github.com/PelagusWallet/pelagus-extension/assets/36986437/aea0d1f9-3ca6-41ae-93c9-dc6f6d52c6fb)
![Screenshot from 2023-09-07 14-22-34](https://github.com/PelagusWallet/pelagus-extension/assets/36986437/35ce79f8-9855-4573-9967-8fa0140185ca)

**Comment by jdowning100** [comment]
Fixed in https://github.com/PelagusWallet/pelagus-extension/pull/84
