### ISSUE TITLE
ShardFromRpcUrl should throw an error when it encounters an unknown rpc

### ISSUE THREAD

**Issue by jdowning100** [PelagusWallet/pelagus-extension#5]
### What would you like to be able to do?

From https://github.com/PelagusWallet/pelagus/pull/3
Currently RPCs from other chains are sent into this function, so throwing an error will break logic that would otherwise perform 'acceptably'. Instead it just logs an error. When we remove RPCs from other chains it should throw an error (break the logic).

**Comment by wizeguyy** [comment]
See https://github.com/PelagusWallet/pelagus/pull/3#discussion_r1253644952 for reference

**Comment by Juuddi** [comment]
No longer relevant
