### ISSUE TITLE
Please include an informative title that describes the bug!

### ISSUE THREAD

**Issue by Friedheilm** [PelagusWallet/pelagus-extension#58]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

During renaming entered long name for the wallet, that can't fit in one line.

### What did not work?

Menu with controls of the wallet on the right side is moved out of boundaries and inaccessible for interaction.
![Screenshot from 2023-09-07 18-20-45](https://github.com/PelagusWallet/pelagus-extension/assets/36986437/693455f5-0770-44a9-a529-c2f8ae24fd89)

### Version

v0.38.1

**Comment by jdowning100** [comment]
Fixed in https://github.com/PelagusWallet/pelagus-extension/pull/59
