### ISSUE TITLE
Unable to send any transactions when running on local network without turning wallet off then on

### ISSUE THREAD

**Issue by robschleusner** [PelagusWallet/pelagus-extension#60]
### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Steps to reproduce:
1. Have a wallet that is running on colosseum
2. Start a local node and CPU miner, mining rewards going to wallet addresses
3. Change wallet to local and try to send a TX

![Screenshot 2023-09-11 at 11 31 36 AM](https://github.com/PelagusWallet/pelagus-extension/assets/84946595/8a29e71c-6694-4dc1-880e-5ea8c9b4fbdf)

### What did not work?

TX never went through. Was able to fix by turning wallet off then back on in Manage Extensions page of Chrome. 

### Version

v0.38.1

**Comment by jdowning100** [comment]
I believe this bug is caused by the local node previously being used to sync colosseum. Can you confirm that you synced with colosseum?

**Comment by robschleusner** [comment]
I don't think I had synced with colosseum immediately beforehand. I haven't seen it since, I'll try to reproduce later today
