### ISSUE TITLE
Pelagus is not correctly estimating gas for cross-prime

### ISSUE THREAD

**Issue by robschleusner** [PelagusWallet/pelagus-extension#62]
### What browsers are you seeing the problem on?

Chrome, Brave

### What were you trying to do?

Send an ETX from cyprus-2 to another chain (non-cyprus) and the transaction was getting completely dropped. It had enough gas to leave the wallet, but the money never landed in the destination account. 

The blocks were mining correctly (enough coincident blocks so that the tx should've gone through), but still no funds. Shreekara was able to send cross-prime TX by using a script, and the gas was much higher than pelagus's estimation

Pelagus estimated gas 0x186a0, max fee: 0x218711a09 (9,000,000,009)
Shreekara estimated gas 0xa410, max fee per gas: 0x649534e00 (27,000,000,000)

### What did not work?

The TX never came through. I WAS able to send transactions between chains within the same region. But the gas estimation was not enough to send all the way across prime

### Version

None

### Relevant log output

```shell
Pelagus getTransactionReceipt result:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0x0000393e0478d9ede415e531ecec34a1be6af9392169900c6c0e95790330435a",
        "blockNumber": "0x42b2",
        "contractAddress": null,
        "cumulativeGasUsed": "0xa410",
        "effectiveGasPrice": "0x3b9aca01",
        "etxs": [
            {
                "type": "0x1",
                "nonce": "0x3",
                "gasPrice": null,
                "maxPriorityFeePerGas": "0x218711a00",
                "maxFeePerGas": "0x218711a09",
                "gas": "0x186a0",
                "value": "0x6aaf7c8516d0c0000",
                "input": "0x",
                "to": "0x7684b88843b2556e8fa5e55bf7eb5ce6571f4733",
                "accessList": [],
                "chainId": "0x539",
                "sender": "0x3ae23f1222894604fd5498bc83e7dc2dea853633",
                "hash": "0x98a68f038ab200a864058ccd0dbf3d09c380b03f559cc0b14a9c005ffbabd3ef"
            }
        ],
        "from": "0x3ae23f1222894604fd5498bc83e7dc2dea853633",
        "gasUsed": "0xa410",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "status": "0x1",
        "to": "0x7684b88843b2556e8fa5e55bf7eb5ce6571f4733",
        "transactionHash": "0x3c2aefc53ec4b63e643966ac782f4912253c9217c0a020968e4135e3c78d21d3",
        "transactionIndex": "0x0",
        "type": "0x2"
    }
}


Shreekara getTransactionReceiptLogs:
"result": {
        "blockHash": "0x000013a566adde0373a22128a5c2503a55801a7d43de6504d028d776e99fa09f",
        "blockNumber": "0x9",
        "contractAddress": null,
        "cumulativeGasUsed": "0xa410",
        "effectiveGasPrice": "0x77359400",
        "etxs": [
            {
                "type": "0x1",
                "nonce": "0x2",
                "gasPrice": null,
                "maxPriorityFeePerGas": "0x218711a00",
                "maxFeePerGas": "0x649534e00",
                "gas": "0xa410",
                "value": "0x23",
                "input": "0x",
                "to": "0x63e696b526f6fa5bbedee8c15edb55cb29a164af",
                "accessList": [],
                "chainId": "0x539",
                "sender": "0x0042c33e1d7cd57d5de8c422be76868aaccae287",
                "hash": "0xb9fdd0f7e2c1a9cbdaa8f305f95dae35e3598e7416625d5efa188dd9c364b752"
            }
        ],
        "from": "0x0042c33e1d7cd57d5de8c422be76868aaccae287",
        "gasUsed": "0xa410",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "status": "0x1",
        "to": "0x63e696b526f6fa5bbedee8c15edb55cb29a164af",
        "transactionHash": "0xe5863c2ef7420a7cfe02f4aa4ef619bde4d793ff66b9dfca3827cd23db30f101",
        "transactionIndex": "0x0",
        "type": "0x2"
    }
```

**Comment by robschleusner** [comment]
This was all in local

**Comment by jdowning100** [comment]
<img width="382" alt="Screen Shot 2023-09-13 at 11 12 19 AM" src="https://github.com/PelagusWallet/pelagus-extension/assets/26939949/5f47042c-6097-4ca4-8759-f300c7f7f2cc">
<img width="382" alt="Screen Shot 2023-09-13 at 11 12 25 AM" src="https://github.com/PelagusWallet/pelagus-extension/assets/26939949/04bb3425-c5c1-4d02-ad28-c9715ec3893c">

I was unable to replicate this issue unfortunately. What I did:

- Run a full node in local
- Mine in zone-0-0 (cyprus-1) and zone-1-0 (paxos-1)
- Send a transaction from one of the pre-funded wallets to my pelagus wallet in cyprus-1
- Send a transaction from my pelagus cyprus-1 to my pelagus paxos-1
- Wait about 10 minutes
- Funds show up in my pelagus paxos-1 wallet

Additionally, the max fee you saw in Pelagus of 0x218711a09 (9,000,000,009) wei per gas (9 gwei) is correct. This is because a cross-prime transaction requires 9x the max fee it specified in the origin zone. So if this transaction estimated approx 1 gwei per unit of gas in the origin, it would need approx 9 gwei per unit of gas in the ETX base fee/max fee field to be sent to the destination.

**Comment by robschleusner** [comment]
That makes sense. Not sure why ETXs weren't going through yesterday even after several hours. I reset the local environment and it worked today.
