### ISSUE TITLE
Add "Quai Colosseum Local" network to wallet

### ISSUE THREAD

**Issue by jdowning100** [PelagusWallet/pelagus-extension#67]
### Discord Discussion Link

https://discord.com/channels/1105993972247175229/1117868165771317459/1151905420592562186

### What would you like to be able to do?

The Colosseum network ("Quai Network") in the wallet currently uses the public Colosseum RPC nodes and the "Quai Network Local" network expects the "local" chain id (1337). We should add the ability for a user to connect to Colosseum through a local node via a new network - Quai Colosseum Local. In the future, users should also be able to specify their own RPC urls and their own chain ids.

**Comment by wizeguyy** [comment]
Not sure what the final design would look like, but it would be nice if the wallet discovered which network a particular RPC/node is running, and confirm with the user they want to use that network.

**Comment by Juuddi** [comment]
Finished
