### ISSUE TITLE
[UI Bug] Pin Pelagus Extension GIF not formatted correctly for different sized windows

### ISSUE THREAD

**Issue by robschleusner** [PelagusWallet/pelagus-extension#77]
### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Install pelagus for first time and import wallet. 

### What did not work?

![Screenshot 2023-09-19 at 3 49 21 PM](https://github.com/PelagusWallet/pelagus-extension/assets/84946595/bf02c0dc-1edf-4561-a260-a053c42395e4)

### Version

None

**Comment by jdowning100** [comment]
Fixed in https://github.com/PelagusWallet/pelagus-extension/pull/78
