### ISSUE TITLE
Extension crashes if network goes in and out

### ISSUE THREAD

**Issue by jdowning100** [PelagusWallet/pelagus-extension#89]
### Discord Discussion Link

N/A

### What would you like to be able to do?

If the local network is selected and the node goes offline, the extension crashes. Need to figure out why this happens and fix.

**Comment by Denis2626** [comment]
I am unable to replicate the issue. Is there another way to force the node to go offline other than make stop.

**Comment by jdowning100** [comment]
> I am unable to replicate the issue. Is there another way to force the node to go offline other than make stop.


To replicate:
Start local node
Send a transaction in the wallet
Stop local node
Wait about 10 seconds
You won't be able to change the account or network
After about 30 seconds, close the wallet, you won't be able to reopen
