### ISSUE TITLE
Refactor providerForNetworkOrThrow and remove global shard

### ISSUE THREAD

**Issue by jdowning100** [PelagusWallet/pelagus-extension#90]
### Discord Discussion Link

N/A

### What would you like to be able to do?

The providerForNetworkOrThrow and providerForNetwork function should accept a 'shard' argument that it uses to choose the correct provider, rather than the global shard object. The global shard object was a temporary bandaid and should be removed.

**Comment by Juuddi** [comment]
No longer relevant
